name = "BARS"
uuid = "93b16f6d-36af-4dc8-b800-fb1fd5ea2d37"
authors = ["Adam <adamaker2@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
